services:
  - name: backend
    type: web
    env: python
    region: oregon
    rootDir: ./backend
    buildFilter:
      paths:
        - "backend/**"
    build: |
      pip install -r requirements.txt
      pip install neon-cli
      neon ip-allow add 74.220.48.0/24 74.220.56.0/24 --project-id fancy-truth-11807115 --api-key $NEON_API_KEY
    start: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString
      - key: SANDBOX_URL
        value: http://sandbox:8001
      - key: NEON_API_KEY
        sync: false
  - name: sandbox
    type: web
    env: docker
    region: oregon
    rootDir: ./sandbox
    buildFilter:
      paths:
        - "sandbox/**"
    dockerfilePath: ./sandbox/Dockerfile
    envVars:
      - key: PORT
        value: 8001
